name: Deploy to Server

on:
  push:
    branches:
      - main # or whatever branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /srv/website
            git pull origin main
            export PATH=$HOME/.bun/bin:$PATH
            bun install
            bun run build
